### ISSUE TITLE
Can't find published 1.5 artifacts

### ISSUE THREAD

**Issue by Otann** [guardian/sbt-teamcity-test-reporting-plugin#5]
Hello, guys, i've just tried your plugin and seems abc can't find it in repo.
I checked manually and there is only 1.3 version available:

http://dl.bintray.com/sbt/sbt-plugin-releases/com.gu/sbt-teamcity-test-reporting-plugin/scala_2.9.2/sbt_0.12/

**Comment by philwills** [comment]
Hi @Otann,

1.5 is a release for SBT 0.13:

http://dl.bintray.com/sbt/sbt-plugin-releases/com.gu/sbt-teamcity-test-reporting-plugin/scala_2.10/sbt_0.13/

I believe 1.3 should be fine for 0.12 as the only changes between 1.3  and 1.5 were compatibility changes for 0.13.  There is a note in the README to that effect: "Note that due to a change in SBT's test interface 1.3 is the latest version published for the 0.12 series of SBT."

**Comment by Otann** [comment]
Oh, I get it now.
Thanks for updating readme.
